hreflang.settings:
  type: config_object
  label: 'Hreflang settings'
  mapping:
    x_default:
      type: boolean
      label: 'Add x-default hreflang tag for default language'
    defer_to_content_translation:
      type: boolean
      label: 'Defer to Content Translation hreflang tags on content entity pages'
